# Generated by Django 3.0.2 on 2020-02-06 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_building', models.BooleanField(default=False)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('baseline', models.PositiveIntegerField()),
                ('render', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.Location')),
            ],
        ),
    ]
