# Generated by Django 3.0.2 on 2020-02-19 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_location_has_render'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('baseline', models.PositiveIntegerField(default=0)),
                ('has_render', models.BooleanField(default=False)),
                ('render', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('baseline', models.PositiveIntegerField(default=0)),
                ('has_render', models.BooleanField(default=False)),
                ('remder', models.TextField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Building')),
            ],
            options={
                'ordering': ['building'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('baseline', models.PositiveIntegerField(default=0)),
                ('has_render', models.BooleanField(default=False)),
                ('render', models.TextField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Building')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Floor')),
            ],
            options={
                'ordering': ['building', 'floor'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building', 'floor', 'number'), name='unique_room'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='unique_floor'),
        ),
    ]
