# Generated by Django 3.0.2 on 2020-02-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_auto_20200225_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='baseline',
            new_name='baseline_clients',
        ),
        migrations.RenameField(
            model_name='floor',
            old_name='baseline',
            new_name='baseline_clients',
        ),
        migrations.AddField(
            model_name='building',
            name='baseline_bandwidth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floor',
            name='baseline_bandwidth',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
