# Generated by Django 3.0.2 on 2020-02-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_auto_20200225_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='remder',
            new_name='render',
        ),
    ]
